import { Language } from "@keybr/keyboard";
import { Alphabet, Filter, type PhoneticModel } from "@keybr/phonetic-model";
import { PhoneticModelLoader } from "@keybr/phonetic-model-loader";
import { Field, FieldList, FieldSet, Para } from "@keybr/widget";

export function PseudoWordsSettings() {
  return (
    <PhoneticModelLoader language={Language.ZH_TW}>
      {(model) => <Content model={model} />}
    </PhoneticModelLoader>
  );
}

function Content({ model }: { model: PhoneticModel }) {
  const words = [];
  for (let i = 0; i < 50; i++) {
    words.push(model.nextWord(Filter.empty));
  }
  return (
    <FieldSet legend="Pseudo words">
      <Para>
        Type pseudo words generated by an algorithm according to the phonetic
        rules of your language.
      </Para>

      <FieldList>
        <Field>Alphabet:</Field>
        <Field>
          <Alphabet model={model} />
        </Field>
      </FieldList>

      <FieldList>
        <Field>Example:</Field>
        <Field>
          <em>{words.join(" ")}</em>
        </Field>
      </FieldList>
    </FieldSet>
  );
}
