services:
  keybr:
    image: ghcr.io/linzeyan/keybr.com:bopomofo
    build:
      dockerfile: ./Dockerfile
    volumes:
      - keybr-data:/var/lib/keybr
      - /path/to/env:/etc/keybr/env:ro
    ports:
      - 30044:3000
    restart: unless-stopped

volumes:
  keybr-data:
