/**
 * The readings of the McBopomofo input method, as generated by
 * `generate-zhuyin`. The phrases are lines of a phrase, its keys on the
 * Dachen (大千) layout and its corpus count, separated by tabs, as in
 * "今天\tㄐㄧㄣ ㄊㄧㄢ \t1234". The norm is the total of the scaled counts of
 * the whole corpus, including the phrases without a reading.
 */
export type Readings = {
  readonly norm: number;
  readonly phrases: string;
};

/** McBopomofo scales the phrase counts to favor longer phrases. */
export function phraseScale(phrase: string): number {
  return 2.7 ** ([...phrase].length - 1);
}

type Phrase = {
  readonly keys: string;
  readonly score: number;
};

/**
 * Reads Hanzi as the keys of the Dachen (大千) layout. A run of Hanzi is read
 * as its most likely sequence of phrases, scored the way McBopomofo does,
 * which picks the right reading of most polyphonic characters.
 */
export class ZhuyinReader {
  readonly #phrases = new Map<string, Phrase>();
  readonly #maxLength: number;
  /** The score of a Hanzi without a reading, as rare as a rare Hanzi. */
  readonly #unknown: number;

  constructor({ norm, phrases }: Readings) {
    const score = (phrase: string, count: number) =>
      // The count floor keeps a rare character readable.
      Math.log((phraseScale(phrase) * Math.max(count, 0.5)) / norm);
    let maxLength = 1;
    for (const line of phrases.split("\n")) {
      const [phrase, keys, count] = line.split("\t");
      this.#phrases.set(phrase, { keys, score: score(phrase, Number(count)) });
      maxLength = Math.max(maxLength, [...phrase].length);
    }
    this.#maxLength = maxLength;
    this.#unknown = score("字", 0);
  }

  /**
   * Pairs every Hanzi of the text with its keys, as in "我ㄨㄛˇ們ㄇㄣ˙", while
   * any other char stays as it is. The first tone is typed with the space
   * bar, as in "今ㄐㄧㄣ 天ㄊㄧㄢ", except at the end of the text. A Hanzi
   * without a reading has no keys.
   */
  toGlyphs(text: string): string {
    return text
      .replace(/\p{Script=Han}+/gu, (run) => {
        const chars = [...run];
        const syllables = this.#read(chars);
        return chars.map((char, i) => char + syllables[i]).join("");
      })
      .trimEnd();
  }

  /** Returns the keys of every character. */
  #read(chars: readonly string[]): string[] {
    // best[i] is the last phrase of the most likely reading of the first
    // i characters, the phrases before it are found backwards.
    const best: { score: number; length: number; keys: string }[] = [
      { score: 0, length: 0, keys: "" },
    ];
    for (let i = 1; i <= chars.length; i++) {
      for (let n = 1; n <= Math.min(i, this.#maxLength); n++) {
        const phrase = this.#phrases.get(chars.slice(i - n, i).join(""));
        if (phrase != null) {
          const score = best[i - n].score + phrase.score;
          if (best[i] == null || score > best[i].score) {
            best[i] = { score, length: n, keys: phrase.keys };
          }
        }
      }
      best[i] ??= {
        score: best[i - 1].score + this.#unknown,
        length: 1,
        keys: "",
      };
    }
    const phrases: string[][] = [];
    for (let i = chars.length; i > 0; i -= best[i].length) {
      const { keys } = best[i];
      // A syllable ends with its tone mark, or with the space of a first tone.
      phrases.push(keys === "" ? [""] : keys.match(/[^ˊˇˋ˙ ]+[ˊˇˋ˙ ]/gu)!);
    }
    return phrases.reverse().flat();
  }
}
